name: Build Status

on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start mongodb
      uses: supercharge/mongodb-github-action@1.8.0
    - uses: nixbuild/nix-quick-install-action@v21
    - name: Run tests
      run: |
        nix-shell --command "sbt -DSnippetsContainerTest.mongo=true cachedCiTest"
