name: Build Status

on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Start mongodb
      uses: supercharge/mongodb-github-action@1.8.0

    - name: Setup nix
    - uses: cachix/install-nix-action@v19
      with:
        nix_path: nixpkgs=channel:nixos-22.11
      run: nix-build
    - name: Run tests
      run: |
        nix-shell --command "sbt -DSnippetsContainerTest.mongo=true cachedCiTest"
